# Generated by Django 6.0.4 on 2026-05-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_remove_lesson_scheduled_at_remove_lesson_zoom_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='colab_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Google Colab'),
        ),
    ]
